name: CI / Test, Build, and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-and-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Print additional debug info
        run: |
            echo '=============================Docker Info============================='
            docker info
            echo '=============================Docker Context============================='
            docker context show

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: mereader-app:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
