name: Build and Release Docker Container

on:
    release:
        types: [published]

permissions:
    contents: read
    packages: write

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Log in to Github Container Registry
              run: |
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u wu21-web --password-stdin
                echo "Debug: Docker info: "
                docker info
                echo "Debug: Docker context: "
                docker context show

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build and push Docker image
              uses: docker/build-push-action@v7
              with:
                  context: .
                  push: true
                  tags: ghcr.io/wu21-web/MeReader:${{ github.event.release.tag_name }}